### ISSUE TITLE
hey can i help

### ISSUE THREAD

**Issue by Stilic** [skuqre/Hope-Engine#1]
hi
im the assistant coder of mag engine
can i help you for something on your awesome and cool kade engine fork?
(ok idk if this is a good idea at all)

**Comment by Stilic** [comment]
if yes then give me your discord tag and i talk with you tommorow

**Comment by skuqre** [comment]
sure -- skuqre#7660
what could this something be about?

**Comment by Stilic** [comment]
> sure -- skuqre#7660 what could this something be about?

maybe clean the code a lot and refactor junk shit
