### ISSUE TITLE
[BUG]: Complex accuracy mode issue similar to newer Kade versions

### ISSUE THREAD

**Issue by daisukidaisy** [skuqre/Hope-Engine#12]
### Bug Description

![moment](https://user-images.githubusercontent.com/91840623/187763136-50869694-42d8-4a7d-9ba0-b23a8f5696c3.png)

Hitting early should not result in automatic 100% accuracy. I think you forgot to throw an abs() somewhere in the formula for accuracy, but I'm not sure where.
Kade Engine 1.5.2 (which this is forked from) does not do this, but 1.6 and later do.

### Type of Hope Engine

Compiled (you mess with ".hemc", ".hent", ".hes" files and the like.)

### Version

v0.1.6 (Most recent release

### Platform

Windows (64 bit)

**Comment by skuqre** [comment]
Yep, I didn't throw in an `abs()` in the function that generates the Wife3 value

I kept it as is because I thought it didn't have caveats with negative timing

Fix will be included in next update
