### ISSUE TITLE
[COMPILATION]: Compilation Issue even though I changed nothing here

### ISSUE THREAD

**Issue by daisukidaisy** [skuqre/Hope-Engine#13]
### What Happened?

![image](https://user-images.githubusercontent.com/91840623/188223153-18f2af7f-78ad-4858-95b6-d4161f094f50.png)

I changed none of the above hx files.

EDIT: I updated hxCodec and the part about StageEditor was fixed.

### Command Prompt Logs

```shell
(see image above)
```

### Version

Most recent stable build (from yesterday)

### Platform/Compilation Target

Windows (64 bit)

**Comment by skuqre** [comment]
Must be your flixel being at a version lower than 4.11.0

**Comment by daisukidaisy** [comment]
i have 4.11.0

**Comment by daisukidaisy** [comment]
apparently the Transparency.hx issue is not actually a problem, it still can compile
