### ISSUE TITLE
[BUG]: Spirit's txt file format crashes the game when copied and used in a mods folder mod

### ISSUE THREAD

**Issue by daisukidaisy** [skuqre/Hope-Engine#18]
### Bug Description

I copied and used Spirit's png, txt (which it uses instead of xml) and json in "_characters", and it CRASHES the game when attempting to load.
I am trying to finish porting B-Sides to Hope Engine, and this is the ONLY THING stopping me.

### Crash Logs / Command Prompt Logs

```shell
openfl/display/DisplayObject.hx (line 1399)
openfl/events/EventDispatcher.hx (line 402)
flixel/FlxGame.hx (line 551)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 637)
editors/CharacterEditor.hx (line 176)
editors/CharacterEditor.hx (line 785)
Character.hx (line 121)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)

Error: Null Object Reference
```

### Type of Hope Engine

Compiled (you mess with ".hemc", ".hent", ".hes" files and the like.)

### Version

The built version of PR#17, which does not change any of the .hx files listed in the crash log.

### Platform

Windows (64 bit)

**Comment by skuqre** [comment]
I have no clue why it auto closed that one

Fix will be in next update, in a blue moon
