### ISSUE TITLE
[BUG]: the thing where the background doesnt move properly and just does something

### ISSUE THREAD

**Issue by BlazeTBV** [skuqre/Hope-Engine#20]
### Bug Description

![image](https://user-images.githubusercontent.com/111521802/201710894-5793f6f7-d37d-42cc-b576-e3d767578586.png)

### Type of Hope Engine

Compiled (you mess with ".hemc", ".hent", ".hes" files and the like.)

### Version

0.1.7

### Platform

Windows (64 bit)

**Comment by skuqre** [comment]
Lmao damn

You're on compiled, so you can't

**Comment by BlazeTBV** [comment]
i was on compiled because i was just checking it out. i can compile it in source can u just tell me how
