### ISSUE TITLE
[BUG]: No idea what I'm looking at, here's a crash log

### ISSUE THREAD

**Issue by daisukidaisy** [skuqre/Hope-Engine#6]
### Bug Description

I was in the middle of porting B-Sides to the most recent version of Hope Engine, and as soon as I finished Fresh (B-Side), Boyfriend's death sound played and this crash log generated.
I did not fail the song, as a matter of fact, I nearly 100%ed it and then this happened when I hit the final note.
You tell me what happened, I'm not familiar with this. I may have missed a step, who knows, not me.

### Crash Logs / Command Prompt Logs

```shell
openfl/display/DisplayObject.hx (line 1399)
openfl/events/EventDispatcher.hx (line 402)
flixel/FlxGame.hx (line 551)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 747)
flixel/FlxState.hx (line 203)
PlayState.hx (line 2380)
GameOverSubstate.hx (line 74)

Error: Null Object Reference
```

### Type of Hope Engine

Compiled (you mess with ".hemc", ".hent", ".hes" files and the like.)

### Version

v0.1.3 (Most recent release)

### Platform

Windows (64 bit)

**Comment by skuqre** [comment]
I... forgot to remove the death lock... (i was testing "So Close!")

The null is fixed now though

[new build](https://github.com/skuqre/Hope-Engine/suites/7367009346/artifacts/299186517)
